wic: use part-name fip for fip (instead of ssbl)
Use fip as part-name for fip otherwise tf-a is unable to find the fip
partition:

ERROR:   Could NOT find the fip partition!
ERROR:   BL2: Failure in pre image load handling (-2)

Signed-off-by: Ricardo Salveti <ricardo@foundries.io>